### ISSUE TITLE
Не могу сбилдить проект

### ISSUE THREAD

**Issue by Briahas** [aacidov/DisTypePro-ios#10]
Склонил транк - в проекте не указаны файлы из директории, "под"-а нет. Ветка точно в рабочем состоянии?

**Comment by itruf** [comment]
Хай. В проекте используется cocoapods и имеется podfile. Достаточно установить cocoapods, в терминале открыть папку с podfile'ом и выполнить команду pod update.

**Comment by Briahas** [comment]
Странно, почему подсы не залиты в репоз?
И почему все файлы проекта из директории distype пришлось потом добавлять руками?

**Comment by itruf** [comment]
1. Потому что это не совсем правильно. Тогда изменения в подсах будут перегружать историю комитов. Почитать можно тут: https://guides.cocoapods.org/using/using-cocoapods.html#should-i-check-the-pods-directory-into-source-control
2. Этого не знаю, я давно не ковырялся в последних версиях.

**Comment by Briahas** [comment]
По Вашей ссылке (имхо) вот этот факт:
- The Pod artifacts are guaranteed to be identical to those in the original installation after cloning the repo.

, перевешивает все факты против. Все будут иметь идентичные файлы, и не будет метаний из-за того что кто-то не так себе установил подсы (версия cooapods разная или еще чего)

**Comment by Davarg** [comment]
Поды не должны сливаться, репа должна быть только из файлов приложения, сторонние библиотеки подтягиваются индивидуально.
Проблемы версионности подов решаются через явное указание версии пода в podfile.

**Comment by itruf** [comment]
Оффтоп: Да будет срач.

**Comment by Briahas** [comment]
Ни какого срача. Я предложил - Большинство решило "не сливать". Оки.
