### ISSUE TITLE
Создать структуру БД + методы для работы с ней

### ISSUE THREAD

**Issue by itruf** [aacidov/DisTypePro-ios#2]
Предлагаю Magical Record

**Comment by ibakaidov** [comment]
Я аще хз что это))) я, кстати, всё лето трахался с AVSpeechSynthezator, оказалось, что надо переключить переключалку на корпусе уведомления на вкл.

**Comment by itruf** [comment]
Да я так, на всякий случай, чтобы может быть подошел кто-то и сказал, что надо юзать что-то более крутое.

**Comment by rbugaian** [comment]
Предлагаю использовать Realm.io
https://realm.io

**Comment by itruf** [comment]
Можно, я не против попробовать. @rbugaian добавишь тогда в проект?

**Comment by rbugaian** [comment]
@itruf Добавлю, только чуть позже.

**Comment by Briahas** [comment]
При использовании Реалма столкнулись с проблемами при изменении структур записей. Приходилось переустанавливать приложение. Я б не заморачивался и юзал старую добрую коредату.

**Comment by Davarg** [comment]
Может просто миграцию не делали?

**Comment by Briahas** [comment]
наверное.

Ребята, если вы работали с ним и уверены в нем - пилим на нем.

**Comment by kchugalinskiy** [comment]
Коредата как и реалм несет потенциальную проблему портируемости. Извините за вопрос, а что вообще хранить-то?

**Comment by Briahas** [comment]
Я так понимаю часто используемые фразы. Или - преднабранные фразы. @ibakaidov лучше расскажет. Или почитай на его сайте о программе.

**Comment by ibakaidov** [comment]
https://play.google.com/store/apps/details?id=ru.ibakaidov.distypepro

**Comment by Davarg** [comment]
Я вижу следующие модели, которые могут у нас быть
1. Сообщение (дата создания; тело сообщения; категория, к которой данное выражение относится; идентификатор разговора)
2. Категория слов (дата создания; название категории; идентификатор категории)
3. Разговор (дата создания; идентификатор разговора, название разговора)

Ребята еще раз напомню, что я создал канал в слаке и предлагаю такие вот обсуждения туда перенести distypepro.slack.com
