### ISSUE TITLE
Способ общение

### ISSUE THREAD

**Issue by Davarg** [aacidov/DisTypePro-ios#4]
Предлагаю перенести общение в Slack. Уже создал канал distypepro.slack.com

**Comment by ibakaidov** [comment]
я тоже за слак... создам канал aacidov. жду емейлы

**Comment by Davarg** [comment]
Ваня, если че, канал уже есть, могу отдать тебе модерские привелегии и т.п. 
Вот готовый уже канал distypepro.slack.com
Если вопрос принципиальный, то не проблема, я тебе на почту могу отписаться, ты главное скажи как лучше.

**Comment by Briahas** [comment]
Лучше разбить чаты по программам и иметь общий чат. Коннектюсь на distypepro и aacidov

**Comment by Briahas** [comment]
@Davarg сделай приглашение по емейл в слак.

**Comment by Davarg** [comment]
@Briahas С удовольствием, но мне необходима твоя почта. Ну или ты попробуй сам залогинеться на distypepro.slack.com , у нас там открыто.

**Comment by Briahas** [comment]
@Davarg  в том то и дело, что пробовал - не пускает. Пришли на briahas@gmail.com пожалуйста.

**Comment by Davarg** [comment]
@Briahas твоя правда, сорян, только по инвайтам можно. Я отправил тебе. 
Отпишусь здесь, любой желающий в слаку пусть пишет мне в LinkedIn (у меня в профиле здесь можете найти меня) или здесь оставляйте мыло.
